---
- name: Install libvirt
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - libvirt-daemon-system

- name: Add user to libvirt group
  ansible.builtin.user:
    name: vagrant
    groups: libvirt
    append: true

- name: Ensure libvirt daemon is started
  ansible.builtin.service:
    name: libvirtd
    state: started

- name: Set default network as autostart
  ansible.builtin.command: virsh -c xen:/// net-autostart default
  register: net_autostart
  changed_when: false
  failed_when: net_autostart.rc != 0

- name: Ensure default libvirt network is started
  ansible.builtin.command: virsh -c xen:/// net-start default
  register: net_start
  changed_when: false
  failed_when: net_start.rc != 0

- name: Define libvirt pool
  ansible.builtin.command: virsh -c xen:/// pool-define-as default --type dir --target /data/images
  register: pool_define
  changed_when: false
  failed_when: pool_define.rc != 0

- name: Build libvirt pool
  ansible.builtin.command: virsh -c xen:/// pool-build default
  register: pool_build
  changed_when: false
  failed_when: pool_build.rc != 0

- name: Set libvirt pool as autostart
  ansible.builtin.command: virsh -c xen:/// pool-autostart default
  register: pool_autostart
  changed_when: false
  failed_when: pool_autostart.rc != 0

- name: Ensure libvirt pool is started
  ansible.builtin.command: virsh -c xen:/// pool-start default
  register: pool_start
  changed_when: false
  failed_when: pool_start.rc != 0
