---
- name: Install parted
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - parted

- name: Create a new primary partition with free space left
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      (echo n ; echo p; echo 2; echo ; echo ; echo w) | fdisk /dev/vdc
    executable: /bin/bash
  register: fdisk
  changed_when: false
  failed_when: fdisk.rc != 0

- name: Reread partition table
  ansible.builtin.command: partprobe
  register: partprobe
  changed_when: false
  failed_when: partprobe.rc != 0

- name: Create ext4 filesystem
  ansible.builtin.command: mkfs.ext4 /dev/vdc2
  register: mkfs
  changed_when: false
  failed_when: mkfs.rc != 0

- name: Create /data
  ansible.builtin.file:
    path: /data
    state: directory
    mode: "0755"
    owner: vagrant
    group: vagrant

- name: Mount the new partition on /data
  ansible.posix.mount:
    src: /dev/vdc2
    name: /data
    state: mounted
    fstype: ext4
