---
- name: Provision Debian 12
  hosts: all
  gather_facts: false
  tasks:
    - name: Add user to sudoers
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/99{{ username }}
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        create: true
        mode: "0440"

    - name: Perform system upgrade
      become: true
      ansible.builtin.package:
        name: "*"
        force_apt_get: true
        update_cache: true

    - name: Install useful tools
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
      with_items:
        - git
        - btop
        - vim
        - wget
        - build-essential
        - python3
        - python3-dev
