---
- name: Perform system upgrade
  ansible.builtin.package:
    name: "*"
    force_apt_get: true
    update_cache: true

- name: Install useful tools
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - git
    - htop
    - vim
    - wget
    - build-essential
    - python3
    - python3-dev

- name: Create xenith user
  ansible.builtin.user:
    name: xenith
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    password: "{{ 'xenith' | password_hash('sha512') }}"
