---
- name: Check if Xen is already installed
  become: true
  ansible.builtin.command: xl info
  register: xen_installed
  changed_when: xen_installed.rc == 0
  failed_when: false

# We don't need it for now, kept for future updates
# - name: Check for virtualization extensions in cpuinfo
#   ansible.builtin.shell:
#     cmd: |
#       set -o pipefail
#       egrep '(vmx|svm)' /proc/cpuinfo
#     executable: /bin/bash
#   register: virtualization_extensions
#   changed_when: false
#   failed_when: virtualization_extensions.rc != 0

- name: Install Xen from package
  ansible.builtin.include_tasks: install_from_package.yml
  when: not xen.source and xen_installed.rc != 0

- name: Install Xen from source
  ansible.builtin.include_tasks: install_from_source.yml
  when: xen.source and xen_installed.rc != 0
