---
- name: Post-reboot tasks
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Test successful Xen installation
      ansible.builtin.slurp:
        src: /sys/hypervisor/type
      register: hypertype
      failed_when: hypertype['content'] | b64decode | trim != "xen"

  roles:
    - tools

  # tasks:
  # TODO: add tests virtual machines (windows, linux)
