[book]
title = "Xenith Documentation"
description = """
To-do
"""
authors = ["abel", "kylm"]
language = "en"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/docs/"
git-repository-url = "https://github.com/theo-abel/xenith/tree/main/docs"
edit-url-template = "https://github.com/theo-abel/xenith/edit/main/docs/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
