name: Restrict.Main.Merges.Branch

on:
 pull_request:
   branches:
     - main

jobs:
 restrict-to-merge-branch-qa:
   runs-on: ubuntu-latest
   steps:
     - name: Check merge branch
       if: github.event.pull_request.base.ref == 'main'
       run: |
          REF="${{ github.event.pull_request.head.ref }}"
          if [[ "$REF" ~= ^(qa|dev|staging|hotfix)$ ]]; then
            echo "Merge branch is allowed: $REF"
          else
            echo "Merges to release/QA are only allowed from the dev branch."
            exit 1
          fi
