name: Restrict.Dev.Merges.Branch

on:
 pull_request:
   branches:
     - dev

jobs:
 restrict-to-merge-branch-dev:
   runs-on: ubuntu-latest
   steps:
     - name: Check merge branch
       if: github.event.pull_request.base.ref == 'dev'
       run: |
         ALLOWED_PATTERNS=("feat/*" "docs/*" "fix/*" "chore/*" "style/*" "refactor/*" "perf/*" "test/*")
         BRANCH_ALLOWED=false
         for pattern in "${ALLOWED_PATTERNS[@]}"; do
           if [[ "${{ github.event.pull_request.head.ref }}" == $pattern ]]; then
             BRANCH_ALLOWED=true
             break
           fi
         done
         if [ "$BRANCH_ALLOWED" != true ]; then
           echo "Merges to dev are only allowed from branches matching patterns: ${ALLOWED_PATTERNS[*]}."
           exit 1
         fi
